/*
 * Product Catalog View
 *
 * Product Catalog View
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Source struct {

	// Actual exception occures.
	Exception string `json:"exception,omitempty"`

	// The field for which validation fails.
	Pointer string `json:"pointer,omitempty"`
}
