/*
 * Product Catalog View
 *
 * Product Catalog View
 *
 * API version: 0.0.3-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ProductOffering is made available to Customers at Offering Price level
type ProductOffering struct {

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Version string `json:"version,omitempty"`
}
