/*
 * Product Catalog View
 *
 * Product Catalog View
 *
 * API version: 0.0.3-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RelatedParty struct {

	ReferredType string `json:"@referredType,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Role string `json:"role,omitempty"`

	ValidFor *TimePeriod `json:"validFor,omitempty"`
}
