/*
 * Product Catalog View
 *
 * Product Catalog View
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Offer labels: offer label section where we capture details of offers with respect to channel.
type OfferLabels struct {
	// channel reference of the related entity.
	Channel string `json:"channel,omitempty"`
	// Description of the offer labels.
	Description string `json:"description,omitempty"`
	// Name of the related entity.
	Name string `json:"name,omitempty"`
}
